### ISSUE TITLE
last question icons to be changed to .png (from .svg)

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-core#12]
Seems KoBoCAT doesn't accept svg

**Comment by MartijnR** [comment]
After that the XLSForm needs to be updated with new filenames, and uploaded to server with images.

**Comment by pmusaraj** [comment]
Icons are now in .png in git repo. I also added styling for img element, you just need to remove the display: none; in the two scss files.

**Comment by MartijnR** [comment]
great!
