### ISSUE TITLE
opacity of city placeholder and value is slightly different

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-core#14]

**Comment by MartijnR** [comment]
check both unpopulated and populated value in text input and compare with siblings

**Comment by MartijnR** [comment]
<img width="545" alt="screen shot 2015-09-18 at 2 35 53 pm" src="https://cloud.githubusercontent.com/assets/627350/9970472/9bf1dca2-5e12-11e5-9448-a18b843718a1.png">

**Comment by pmusaraj** [comment]
it's also different in ipad

**Comment by MartijnR** [comment]
Seems fine now. Only img icon looks too different now.

**Comment by pmusaraj** [comment]
im icon looks different in terms of spacing, or how?

**Comment by MartijnR** [comment]
It was opacity, but is resolved now. Sorry for late response.
