### ISSUE TITLE
fine-tuning slider widget

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-core#17]
not urgent
- larger current value bubble
- larger & white slider handle
- remove green border around images

**Comment by pmusaraj** [comment]
this is mostly fixed, so closing.

**Comment by MartijnR** [comment]
Did you commit this? I see the border is gone. But imo at least the value bubble should be more prominent (it seems the dropbox design is no longer accessible - but it was quite large).

**Comment by pmusaraj** [comment]
Made a new commit now, making the bubble bigger. Let me know if this works.

**Comment by MartijnR** [comment]
Yes, looks good to me!
