### ISSUE TITLE
Add footer according to PSD design

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/enketo-core#18]

**Comment by MartijnR** [comment]
Not sure if this referred to an old state or the current state (haven't seen design). Current state:
<img width="1585" alt="screen shot 2015-09-18 at 5 04 52 pm" src="https://cloud.githubusercontent.com/assets/627350/9972874/70b17376-5e27-11e5-90da-59548e08a4e5.png">

**Comment by pmusaraj** [comment]
Fixed in f7ac919

Should look like this https://monosnap.com/file/YQsLqBoWBUqujxhu6ECQg5t8H2svRK
