### ISSUE TITLE
17 tall images to be created

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-core#25]
<img width="376" alt="screen shot 2015-09-20 at 4 54 37 pm" src="https://cloud.githubusercontent.com/assets/627350/9983427/52419a50-5fb8-11e5-99a2-59361c478a9a.png">

**Comment by pmusaraj** [comment]
Yes, I will prepare all these images tonight. 
PM

**Comment by pmusaraj** [comment]
Here are the 17 icons, in 175x400 format: https://dl.dropboxusercontent.com/u/1042893/tall-icons.zip

**Comment by MartijnR** [comment]
:+1:
