### ISSUE TITLE
Error states to be fine-tuned

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-core#5]
<img width="718" alt="screen shot 2015-09-18 at 11 17 54 am" src="https://cloud.githubusercontent.com/assets/627350/9965940/f6a9d2ce-5df6-11e5-9c55-29667d5d98a3.png">

**Comment by MartijnR** [comment]
<img width="370" alt="screen shot 2015-09-18 at 11 54 22 am" src="https://cloud.githubusercontent.com/assets/627350/9966786/0bccfd16-5dfc-11e5-90ea-2347350f195f.png">

**Comment by MartijnR** [comment]
<img width="544" alt="screen shot 2015-09-21 at 9 58 28 am" src="https://cloud.githubusercontent.com/assets/627350/9997063/6678e28c-6047-11e5-8a24-4fa12f84d655.png">

**Comment by MartijnR** [comment]
<img width="517" alt="screen shot 2015-09-21 at 10 08 53 am" src="https://cloud.githubusercontent.com/assets/627350/9997330/cc154a62-6048-11e5-8d58-6927b137910a.png">

**Comment by pmusaraj** [comment]
These should now be fixed in the latest commit, 7c035a0

**Comment by MartijnR** [comment]
Nice!
